# Generated by Django 5.0.2 on 2024-06-13 12:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_bairro_alter_user_cep_alter_user_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arquivo',
            field=models.FileField(blank=True, default='', null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='especialidade',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ferramentas',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='idiomas',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='link_video',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logo_empresa',
            field=models.ImageField(blank=True, default='', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profissao',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
