# Generated by Django 5.0.2 on 2024-06-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_arquivo_user_biografia_user_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('kenai', 'Kenai')], max_length=10),
        ),
    ]
