# Generated by Django 5.0.2 on 2024-06-13 11:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_empresa', models.ImageField(upload_to='logos/')),
                ('biografia', ckeditor.fields.RichTextField()),
                ('profissao', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=255)),
                ('ferramentas', models.CharField(max_length=255)),
                ('idiomas', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('link_video', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=255)),
                ('button_color', models.CharField(max_length=255)),
                ('text_color', models.CharField(max_length=255)),
                ('font_size', models.CharField(max_length=255)),
                ('font_family', models.CharField(max_length=255)),
                ('border_radius', models.CharField(max_length=255)),
            ],
        ),
    ]
