# Generated by Django 5.0.2 on 2024-06-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_applicant_id_alter_bookmarkjob_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='proporcional',
            field=models.CharField(choices=[('1', 'horizontal'), ('2', 'quadrado'), ('3', 'vertical'), ('4', 'outro')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'Edição de vídeo'), ('2', 'Captação de imagem'), ('3', 'Design Gráfico'), ('4', 'Web Design'), ('5', 'Animação 2d/3d'), ('6', 'Motion Designer'), ('7', 'Produtor'), ('8', 'Roteirista'), ('9', 'Social Média')], max_length=1),
        ),
    ]
