# Generated by Django 5.0.2 on 2024-06-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_job_proporcional_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tempo_video',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
