# Generated by Django 5.0.2 on 2024-06-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_remove_job_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
