# Generated by Django 5.0.2 on 2024-06-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_remove_job_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1', 'Buscando Profissional'), ('2', 'Em andamento'), ('3', 'Aprovação do Cliente'), ('4', 'Solicitado Alteração'), ('5', 'Aguardando Pagamento'), ('6', 'Finalizado'), ('7', 'Cancelado')], default='1', max_length=1),
        ),
    ]
