# Generated by Django 5.0.2 on 2024-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
    ]
