# Generated by Django 5.0.2 on 2024-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_alter_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='alteracao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
